### PR TITLE
feat: add interval field to AnnounceHostRequest

### PR DESCRIPTION
**Pull request by BruceAko**
## Description

Add interval field to AnnounceHostRequest, so that scheduler can detect peer survivability and clear offline peer metadata.

## Related Issue

https://github.com/dragonflyoss/Dragonfly2/issues/3350

### CODE REVIEW

**Review by gaius-qi — CHANGES_REQUESTED** [review]
Add interval to. `proto/scheduler.proto` for Rust client.

**Comment by BruceAko** [comment]
> Add interval to. `proto/scheduler.proto` for Rust client.

Done. Please review it again, thanks.

**Review by gaius-qi — CHANGES_REQUESTED** [review]
Update `crate` version in `Cargo.toml`.

**Comment by BruceAko** [comment]
> Update `crate` version in `Cargo.toml`.

Done @gaius-qi

**Review by gaius-qi — APPROVED** [review]
LGTM

**Pull request merged**
